const constants = {
  quote_num: { value: 'Quote Number', sortOrder: 1 },
  customer: { value: 'Customer', sortOrder: 2 },
  end_customer: { value: 'End Customer', sortOrder: 3 },
  name: { value: 'Channel', sortOrder: 4 },
  created_by: { value: 'Created By', sortOrder: 5 },
  created_date: { value: 'Created Date', sortOrder: 6 },
  modified_date: { value: 'Modified Date', sortOrder: 7 },
  workflow_status: { value: 'Status' },
  total_dollars: { value: 'Total Value' },
  display_name: { value: 'Name', sortOrder: 1 },
  account_num: { value: 'Account Number', sortOrder: 2 },
  status: { value: 'Status', sortOrder: 3 },
  type: { value: 'Type', sortOrder: 4 },
  display: { value: 'Segment', sortOrder: 5 },
  location: { value: 'Location' },
  expiration_date: { value: 'Expiration Date' },
  program: { value: 'Program' },
  assembly: { value: 'Assembly' },
  category: { value: 'Category' },
  geography: { value: 'Geography' },
  country: { value: 'Country' },
  state: { value: 'State' },
  city: { value: 'City' },
  zip: { value: 'ZIP' },
  type_key: { value: 'Level' },
};

export default constants;