const constants = {
  quote_num: { value: 'Quote Number', sortOrder: 1 },
  customer: { value: 'Customer', sortOrder: 2 },
  end_customer: { value: 'End Customer', sortOrder: 3 },
  name: { value: 'Channel', sortOrder: 4 },
  created_by: { value: 'Created By', sortOrder: 5 },
  created_date: { value: 'Created Date', sortOrder: 6 },
  modified_date: { value: 'Modified Date', sortOrder: 7 },
  workflow_status: { value: 'Status', sortOrder: 100 },
  total_dollars: { value: 'Total Value', sortOrder: 100 },
  display_name: { value: 'Name', sortOrder: 1 },
  account_num: { value: 'Account Number', sortOrder: 2 },
  status: { value: 'Status', sortOrder: 3 },
  type: { value: 'Type', sortOrder: 4 },
  display: { value: 'Segment', sortOrder: 5 },
  location: { value: 'Location', sortOrder: 100 },
  expiration_date: { value: 'Expiration Date', sortOrder: 100 },
  program: { value: 'Program', sortOrder: 100 },
  assembly: { value: 'Assembly', sortOrder: 100 },
  category: { value: 'Category', sortOrder: 100 },
  geography: { value: 'Geography', sortOrder: 100 },
  country: { value: 'Country', sortOrder: 100 },
  state: { value: 'State', sortOrder: 100 },
  city: { value: 'City', sortOrder: 100 },
  zip: { value: 'ZIP', sortOrder: 100 },
  type_key: { value: 'Level', sortOrder: 100 },
};

export default constants;